"use strict";
const SYMBOLS=["合","乙","老","下老","四","上","中","尺","工","五","六","七","八","○","★","｜"];
const SAMPLE=[["上","上","上","上","工","○","合","○","四","○","四","○"],["四","○","四","○","中","五","六","工","五","中","工","中"],["四","七","六","工","五","中","工","中","上","上","上","合"],["五","中","工","中","上","上","上","上","上","上","工","四"],["中","五","中","合","上","上","上","合","四","七","六","工"],["中","上","四","合","中","五","中","合","中","工","中","合"],["四","四","中","工","五","七","工","四","五","七","工","中"],["五","七","工","四","五","七","工","中","中","上","上","合"],["工","○","合","○","四","○","四","○","四","四","中","工"],["中","五","六","工","五","中","工","中","上","上","上","上"]];
const TUNING_MAP={"本調子":{"合":1,"乙":2,"老":3,"下老":4,"四":5,"上":6,"中":7,"尺":8,"工":9,"五":10,"六":11,"七":12,"八":13},"二揚げ":{"合":1,"乙":2,"老":3,"下老":4,"四":6,"上":7,"中":14,"尺":8,"工":8,"五":10,"六":11,"七":12,"八":13},"三下げ":{"合":1,"乙":2,"老":3,"下老":4,"四":5,"上":6,"中":7,"尺":8,"工":8,"五":9,"六":10,"七":15,"八":12}};
const $=id=>document.getElementById(id); let state,selectedSymbol="合",selectedCol=0,history=[],audioCtx=null,activeNodes=[],playToken=0;
const defaultState=()=>({version:1,title:"童神",author:"沖縄童謡",tuning:"本調子",tempo:100,columns:SAMPLE.map(notes=>({notes:[...notes],lyrics:""}))});
function safeState(raw){if(!raw||!Array.isArray(raw.columns))throw new Error("譜面データの形式が正しくありません。");return{version:1,title:String(raw.title||"無題").slice(0,60),author:String(raw.author||"").slice(0,60),tuning:TUNING_MAP[raw.tuning]?raw.tuning:"本調子",tempo:Math.min(180,Math.max(40,Number(raw.tempo)||100)),columns:raw.columns.slice(0,30).map(c=>({notes:Array.from({length:12},(_,i)=>SYMBOLS.includes(c?.notes?.[i])?c.notes[i]:""),lyrics:String(c?.lyrics||"").slice(0,40)}))};}
function load(){try{state=safeState(JSON.parse(localStorage.getItem("kunkunshi-score")||"null"));}catch{state=defaultState();} if(!state)state=defaultState();}
function snapshot(){history.push(JSON.stringify(state));if(history.length>30)history.shift();}
function persist(){localStorage.setItem("kunkunshi-score",JSON.stringify(state));$("saveState").textContent="保存済み";setTimeout(()=>$("saveState").textContent="自動保存",1000);}
function syncFields(){$("title").value=state.title;$("author").value=state.author;$("tuning").value=state.tuning;$("tempo").value=String(state.tempo);$("tempoOut").value=String(state.tempo);$("paperTitle").textContent=state.title||"無題";$("paperMeta").textContent=[state.author,state.tuning].filter(Boolean).join("・");}
function render(){syncFields();const score=$("score");score.replaceChildren();state.columns.forEach((col,ci)=>{const node=$("columnTemplate").content.firstElementChild.cloneNode(true);node.classList.toggle("selected",ci===selectedCol);const select=node.querySelector(".colSelect");select.textContent=String(ci+1);select.onclick=()=>{selectedCol=ci;render();};const cells=node.querySelector(".noteCells");col.notes.forEach((symbol,ri)=>{const b=document.createElement("button");b.className="noteCell";b.textContent=symbol;b.dataset.col=String(ci);b.dataset.row=String(ri);b.setAttribute("aria-label",`${ci+1}列 ${ri+1}番 ${symbol||"空欄"}`);b.onclick=()=>editCell(ci,ri);cells.append(b);});const lyrics=node.querySelector(".lyrics");lyrics.value=col.lyrics;lyrics.onchange=()=>{snapshot();col.lyrics=lyrics.value;persist();};score.append(node);});}
function editCell(ci,ri){snapshot();state.columns[ci].notes[ri]=state.columns[ci].notes[ri]===selectedSymbol?"":selectedSymbol;selectedCol=ci;persist();render();}
function buildPalette(){const root=$("palette");SYMBOLS.forEach(s=>{const b=document.createElement("button");b.className="symbol";b.textContent=s;b.onclick=()=>{selectedSymbol=s;[...root.children].forEach(x=>x.classList.remove("active"));b.classList.add("active");};if(s===selectedSymbol)b.classList.add("active");root.append(b);});}
function updateMeta(){snapshot();state.title=$("title").value;state.author=$("author").value;state.tuning=$("tuning").value;state.tempo=Number($("tempo").value);persist();syncFields();}
function stop(){playToken++;activeNodes.forEach(n=>{try{n.stop();}catch{}});activeNodes=[];document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));$("playStatus").textContent="停止中";}
function pluck(freq,start,duration){if(!audioCtx)return;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain(),filter=audioCtx.createBiquadFilter();osc.type="triangle";osc.frequency.setValueAtTime(freq,start);filter.type="lowpass";filter.frequency.value=1900;gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.32,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+Math.min(duration,.65));osc.connect(filter).connect(gain).connect(audioCtx.destination);osc.start(start);osc.stop(start+Math.min(duration+.1,.8));activeNodes.push(osc);}
async function play(){stop();try{audioCtx=audioCtx||new AudioContext();await audioCtx.resume();}catch{$("playStatus").textContent="このブラウザでは音を再生できません";return;}const token=++playToken,beat=60/state.tempo,base=Number($("basePitch").value),events=[];state.columns.forEach((c,ci)=>c.notes.forEach((s,ri)=>events.push({s,ci,ri})));$("playStatus").textContent="演奏中";let when=audioCtx.currentTime+.08;events.forEach((e,i)=>{const idx=TUNING_MAP[state.tuning][e.s];if(idx)pluck(base*Math.pow(2,(idx-1)/12),when,beat*.9);setTimeout(()=>{if(token!==playToken)return;document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));document.querySelector(`[data-col="${e.ci}"][data-row="${e.ri}"]`)?.classList.add("playing");if(i===events.length-1)setTimeout(stop,beat*900);},Math.max(0,(when-audioCtx.currentTime)*1000));when+=beat;});}
function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${(state.title||"工工四").replace(/[\\/:*?\"<>|]/g,"_")}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function bind(){["title","author","tuning"].forEach(id=>$(id).addEventListener("change",updateMeta));$("tempo").oninput=()=>{$("tempoOut").value=$("tempo").value;};$("tempo").onchange=updateMeta;$("sampleBtn").onclick=()=>{if(confirm("現在の譜面を童神の見本に置き換えますか？")){snapshot();state=defaultState();persist();render();}};$("newBtn").onclick=()=>{if(confirm("新しい空の譜面を作りますか？")){snapshot();state={...defaultState(),title:"無題",author:"",columns:Array.from({length:8},()=>({notes:Array(12).fill(""),lyrics:""}))};persist();render();}};$("addColBtn").onclick=()=>{snapshot();state.columns.splice(selectedCol+1,0,{notes:Array(12).fill(""),lyrics:""});selectedCol++;persist();render();};$("removeColBtn").onclick=()=>{if(state.columns.length<=1)return;snapshot();state.columns.splice(selectedCol,1);selectedCol=Math.max(0,selectedCol-1);persist();render();};$("eraseBtn").onclick=()=>{snapshot();state.columns[selectedCol].notes.fill("");persist();render();};$("undoBtn").onclick=()=>{const prev=history.pop();if(prev){state=safeState(JSON.parse(prev));persist();render();}};$("exportBtn").onclick=download;$("printBtn").onclick=()=>window.print();$("playBtn").onclick=play;$("stopBtn").onclick=stop;$("importFile").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{snapshot();state=safeState(JSON.parse(await file.text()));persist();render();}catch(err){alert(err instanceof Error?err.message:"読み込みに失敗しました。");}finally{e.target.value="";}};document.addEventListener("visibilitychange",()=>{if(document.hidden)stop();});window.addEventListener("beforeunload",stop);}
load();buildPalette();bind();render();if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
