"use strict";

const SYMBOLS=["合","乙","老","下老","四","上","中","尺","工","五","六","七","八","○"];
const SAMPLE=[["上","上","上","上","工","○","合","○","四","○","四","○"],["四","○","四","○","中","五","六","工","五","中","工","中"],["四","七","六","工","五","中","工","中","上","上","上","合"],["五","中","工","中","上","上","上","上","上","上","工","四"],["中","五","中","合","上","上","上","合","四","七","六","工"],["中","上","四","合","中","五","中","合","中","工","中","合"],["四","四","中","工","五","七","工","四","五","七","工","中"],["五","七","工","四","五","七","工","中","中","上","上","合"],["工","○","合","○","四","○","四","○","四","四","中","工"],["中","五","六","工","五","中","工","中","上","上","上","上"]];
const AUDIO_FILES={"合":"合.wav","乙":"乙.wav","老":"老.wav","下老":"下老.wav","四":"四.wav","上":"上.wav","中":"中.wav","尺":"尺.wav","工":"工.wav","五":"五.wav","六":"六.wav","七":"七.wav","八":"八.wav"};
const TUNING_AUDIO={"本調子":{},"二揚げ":{"四":"二揚四.wav","上":"二揚上.wav","中":"二揚_中.wav"},"三下げ":{"七":"三下七.wav"}};
const $=id=>document.getElementById(id);
let state,selectedSymbol="合",selectedCol=0,cursorRow=0,inputHalfPending=false,history=[],audioCtx=null,activeSources=[],playToken=0,noteSize="normal",technique="",lyricTool="";
const audioBuffers=new Map();

const blankNote=()=>({main:"",half:"",mainSmall:false,halfSmall:false,mainTech:"",halfTech:""});
const blankColumn=()=>({notes:Array.from({length:12},blankNote),lyrics:"",lyricMarks:[]});
const defaultState=()=>({version:2,title:"童神",author:"沖縄童謡",tuning:"本調子",tempo:100,columns:SAMPLE.map(values=>({notes:values.map(main=>({...blankNote(),main})),lyrics:"",lyricMarks:[]}))});
function normalizeNote(value){if(typeof value==="string")return{...blankNote(),main:SYMBOLS.includes(value)?value:""};const n=blankNote();if(value&&typeof value==="object"){n.main=SYMBOLS.includes(value.main)?value.main:"";n.half=SYMBOLS.includes(value.half)?value.half:"";n.mainSmall=Boolean(value.mainSmall);n.halfSmall=Boolean(value.halfSmall);n.mainTech=["uchi","kake"].includes(value.mainTech)?value.mainTech:"";n.halfTech=["uchi","kake"].includes(value.halfTech)?value.halfTech:"";}return n;}
function safeState(raw){if(!raw||!Array.isArray(raw.columns))throw new Error("譜面データの形式が正しくありません。");return{version:2,title:String(raw.title||"無題").slice(0,60),author:String(raw.author||"").slice(0,60),tuning:["本調子","二揚げ","三下げ"].includes(raw.tuning)?raw.tuning:"本調子",tempo:Math.min(180,Math.max(40,Number(raw.tempo)||100)),columns:raw.columns.slice(0,30).map(c=>({notes:Array.from({length:12},(_,i)=>normalizeNote(c?.notes?.[i])),lyrics:String(c?.lyrics||"").slice(0,40),lyricMarks:Array.isArray(c?.lyricMarks)?c.lyricMarks.filter(m=>m&&["start","end","open","filled"].includes(m.type)&&Number.isInteger(m.row)&&m.row>=0&&m.row<12).slice(0,24):[]}))};}
function load(){try{state=safeState(JSON.parse(localStorage.getItem("kunkunshi-score")||"null"));}catch{state=defaultState();}if(!state)state=defaultState();}
function snapshot(){history.push(JSON.stringify(state));if(history.length>30)history.shift();}
function persist(){localStorage.setItem("kunkunshi-score",JSON.stringify(state));$("saveState").textContent="保存済み";setTimeout(()=>$("saveState").textContent="自動保存",1000);}
function syncFields(){$("title").value=state.title;$("author").value=state.author;$("tuning").value=state.tuning;$("tempo").value=String(state.tempo);$("tempoOut").value=String(state.tempo);$("paperTitle").textContent=state.title||"無題";$("paperMeta").textContent=[state.author,state.tuning].filter(Boolean).join("・");}
function makeNoteButton(ci,ri,slot,note){const b=document.createElement("button"),symbol=note[slot];b.className=`${slot==="main"?"noteCell":"halfCell"}${note[`${slot}Small`]?" kubanchi":""}`;if(ci===selectedCol&&ri===cursorRow&&slot==="main")b.classList.add("current");b.dataset.col=String(ci);b.dataset.row=String(ri);b.dataset.slot=slot;b.setAttribute("aria-label",`${ci+1}列 ${ri+1}拍 ${slot==="half"?"後半":"頭"} ${symbol||"空欄"}`);if(symbol){const text=document.createElement("span");text.textContent=symbol;b.append(text);const tech=note[`${slot}Tech`];if(tech){const mark=document.createElement("i");mark.textContent=tech==="uchi"?"、":"┐";b.append(mark);}}else if(slot==="half")b.textContent="＋";b.onclick=()=>editCell(ci,ri,slot);return b;}
function render(){syncFields();const score=$("score");score.replaceChildren();state.columns.forEach((col,ci)=>{const node=$("columnTemplate").content.firstElementChild.cloneNode(true);node.classList.toggle("selected",ci===selectedCol);node.classList.toggle("noLyrics",!col.lyrics.trim()&&col.lyricMarks.length===0);const select=node.querySelector(".colSelect");select.textContent=String(ci+1);select.onclick=()=>{selectedCol=ci;cursorRow=0;render();};const cells=node.querySelector(".noteCells");col.notes.forEach((note,ri)=>{const beat=document.createElement("div");beat.className="beat";beat.append(makeNoteButton(ci,ri,"main",note),makeNoteButton(ci,ri,"half",note));cells.append(beat);});const lyrics=node.querySelector(".lyrics");lyrics.value=col.lyrics;lyrics.onchange=()=>{snapshot();col.lyrics=lyrics.value;persist();render();};const marks=node.querySelector(".lyricMarks");for(let row=0;row<12;row++){const mark=document.createElement("button"),found=col.lyricMarks.find(m=>m.row===row);mark.className="lyricMark";mark.textContent=found?({start:"○",end:"□",open:"○↳",filled:"●↳"}[found.type]):"";mark.onclick=()=>editLyricMark(ci,row);marks.append(mark);}score.append(node);});updateInputStatus();}
function editCell(ci,ri,slot){snapshot();selectedCol=ci;cursorRow=ri;const n=state.columns[ci].notes[ri];if(n[slot]===selectedSymbol){n[slot]="";n[`${slot}Tech`]="";}else{n[slot]=selectedSymbol;n[`${slot}Small`]=noteSize==="small";n[`${slot}Tech`]=technique;}persist();render();}
function setHalfPending(value){inputHalfPending=value;$("beatInputBtn").classList.toggle("active",!value);$("halfInputBtn").classList.toggle("active",value);updateInputStatus();}
function updateInputStatus(){const status=$("inputStatus");if(status)status.textContent=`${selectedCol+1}列・${cursorRow+1}拍目へ${inputHalfPending?"半拍":"1拍"}入力`;}
function advanceCursor(){cursorRow++;if(cursorRow>=12){cursorRow=0;if(selectedCol<state.columns.length-1)selectedCol++;}}
function insertFromKeypad(symbol,half=inputHalfPending){if(!SYMBOLS.includes(symbol))return;snapshot();selectedSymbol=symbol;const slot=half?"half":"main",note=state.columns[selectedCol].notes[cursorRow];note[slot]=symbol;note[`${slot}Small`]=noteSize==="small";note[`${slot}Tech`]=technique;advanceCursor();setHalfPending(false);persist();render();}
function handleKeyboard(event){const target=event.target;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement)return;if(event.ctrlKey&&(event.code==="Slash"||event.code==="NumpadDivide")){event.preventDefault();insertFromKeypad("下老",event.shiftKey);return;}const map={Digit7:"合",Numpad7:"合",Digit8:"乙",Numpad8:"乙",Digit9:"老",Numpad9:"老",NumpadMultiply:"八",Digit4:"四",Numpad4:"四",Digit5:"上",Numpad5:"上",Digit6:"中",Numpad6:"中",Minus:"尺",NumpadSubtract:"尺",Digit1:"工",Numpad1:"工",Digit2:"五",Numpad2:"五",Digit3:"六",Numpad3:"六",NumpadAdd:"七",Equal:"七"},symbol=map[event.code];if(!symbol)return;event.preventDefault();const half=event.shiftKey&&event.code!=="Equal";insertFromKeypad(symbol,half);}
function editLyricMark(ci,row){if(!lyricTool){alert("先に「歌の記号」を選んでください。");return;}snapshot();const marks=state.columns[ci].lyricMarks,index=marks.findIndex(m=>m.row===row);if(index>=0&&marks[index].type===lyricTool)marks.splice(index,1);else if(index>=0)marks[index]={row,type:lyricTool};else marks.push({row,type:lyricTool});selectedCol=ci;persist();render();}
function buildPalette(){const root=$("palette");SYMBOLS.forEach(s=>{const b=document.createElement("button");b.className="symbol";b.textContent=s;b.onclick=()=>{selectedSymbol=s;[...root.children].forEach(x=>x.classList.remove("active"));b.classList.add("active");};if(s===selectedSymbol)b.classList.add("active");root.append(b);});}
function setChoice(ids,callback){ids.forEach(id=>$(id).onclick=()=>{ids.forEach(x=>$(x).classList.toggle("active",x===id));callback(id);});}
function updateMeta(){snapshot();state.title=$("title").value;state.author=$("author").value;state.tuning=$("tuning").value;state.tempo=Number($("tempo").value);persist();syncFields();}
function audioFile(symbol){return TUNING_AUDIO[state.tuning]?.[symbol]||AUDIO_FILES[symbol]||"";}
async function getBuffer(file){if(audioBuffers.has(file))return audioBuffers.get(file);const response=await fetch(`audio/${encodeURIComponent(file)}`);if(!response.ok)throw new Error(`音源 ${file} を読み込めません。`);const buffer=await audioCtx.decodeAudioData(await response.arrayBuffer());audioBuffers.set(file,buffer);return buffer;}
function stop(){playToken++;activeSources.forEach(source=>{try{source.stop();}catch{}});activeSources=[];document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));$("playStatus").textContent="停止中";}
function playBuffer(buffer,when,small){const source=audioCtx.createBufferSource(),gain=audioCtx.createGain();source.buffer=buffer;gain.gain.value=small?.4:1;source.connect(gain).connect(audioCtx.destination);source.start(when);activeSources.push(source);}
async function play(){stop();try{audioCtx=audioCtx||new AudioContext();await audioCtx.resume();const token=++playToken,beat=60/state.tempo,events=[];let beatIndex=0;state.columns.forEach((col,ci)=>col.notes.forEach((note,ri)=>{if(note.main&&note.main!=="○")events.push({symbol:note.main,ci,ri,slot:"main",small:note.mainSmall,time:beatIndex});if(note.half&&note.half!=="○")events.push({symbol:note.half,ci,ri,slot:"half",small:note.halfSmall,time:beatIndex+.5});beatIndex++;}));if(!events.length){$("playStatus").textContent="音が入力されていません";return;}$("playStatus").textContent="三線音源を準備中";const unique=[...new Set(events.map(e=>audioFile(e.symbol)))];await Promise.all(unique.map(getBuffer));if(token!==playToken)return;$("playStatus").textContent="演奏中";const start=audioCtx.currentTime+.12;events.forEach((e,index)=>{const when=start+e.time*beat;playBuffer(audioBuffers.get(audioFile(e.symbol)),when,e.small);setTimeout(()=>{if(token!==playToken)return;document.querySelectorAll(".playing").forEach(n=>n.classList.remove("playing"));document.querySelector(`[data-col="${e.ci}"][data-row="${e.ri}"][data-slot="${e.slot}"]`)?.classList.add("playing");if(index===events.length-1)setTimeout(stop,900);},Math.max(0,(when-audioCtx.currentTime)*1000));});}catch(error){stop();$("playStatus").textContent=error instanceof Error?error.message:"音源の再生に失敗しました";}}
function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${(state.title||"工工四").replace(/[\\/:*?\"<>|]/g,"_")}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function bind(){["title","author","tuning"].forEach(id=>$(id).addEventListener("change",updateMeta));$("tempo").oninput=()=>{$("tempoOut").value=$("tempo").value;};$("tempo").onchange=updateMeta;setChoice(["normalBtn","kubanchiBtn"],id=>noteSize=id==="kubanchiBtn"?"small":"normal");setChoice(["techNoneBtn","uchiBtn","kakeBtn"],id=>technique=id==="uchiBtn"?"uchi":id==="kakeBtn"?"kake":"");document.querySelectorAll("[data-lyric-symbol]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-lyric-symbol]").forEach(x=>x.classList.remove("active"));b.classList.add("active");lyricTool=b.dataset.lyricSymbol||"";});$("sampleBtn").onclick=()=>{if(confirm("現在の譜面を童神の見本に置き換えますか？")){snapshot();state=defaultState();persist();render();}};$("newBtn").onclick=()=>{if(confirm("新しい空の譜面を作りますか？")){snapshot();state={...defaultState(),title:"無題",author:"",columns:Array.from({length:8},blankColumn)};persist();render();}};$("addColBtn").onclick=()=>{snapshot();state.columns.splice(selectedCol+1,0,blankColumn());selectedCol++;persist();render();};$("removeColBtn").onclick=()=>{if(state.columns.length<=1)return;snapshot();state.columns.splice(selectedCol,1);selectedCol=Math.max(0,selectedCol-1);persist();render();};$("eraseBtn").onclick=()=>{snapshot();state.columns[selectedCol].notes=Array.from({length:12},blankNote);persist();render();};$("undoBtn").onclick=()=>{const prev=history.pop();if(prev){state=safeState(JSON.parse(prev));persist();render();}};$("exportBtn").onclick=download;$("printBtn").onclick=()=>window.print();$("playBtn").onclick=play;$("stopBtn").onclick=stop;$("importFile").onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{snapshot();state=safeState(JSON.parse(await file.text()));persist();render();}catch(error){alert(error instanceof Error?error.message:"読み込みに失敗しました。");}finally{event.target.value="";}};document.addEventListener("visibilitychange",()=>{if(document.hidden)stop();});window.addEventListener("beforeunload",stop);}
function bindKeyboardInput(){$("beatInputBtn").onclick=()=>setHalfPending(false);$("halfInputBtn").onclick=()=>setHalfPending(!inputHalfPending);document.querySelectorAll("[data-note]").forEach(button=>button.addEventListener("click",()=>insertFromKeypad(button.dataset.note||"")));document.addEventListener("keydown",handleKeyboard);}
load();buildPalette();bind();bindKeyboardInput();render();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{});
